### ISSUE TITLE
Explore supporting font fallback

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/scribus#110]
Fonts often support one or very few scripts only and fonts for complex script often has no Latin glyphs or glyphs of bad quality, so supporting font fallback is crucial.

One idea would to allow configuring font fallback per script, language or both. It probably should be part of the character or paragraph style.

**Comment by luzpaz** [comment]
Related: https://bugs.scribus.net/view.php?id=9611 ?

**Comment by khaledhosny** [comment]
Looks related, yes.

**Comment by Fahad-Alsaidi** [comment]
I am interested in implement this feature. My initial plan:
1.  add font fallback setting in character style. This will be for one language (for now) and you can set font size for that font.
2.  when drawing a glyph if its id == 0, then find its language and use correspond font fallback to render that font.
3.  apply setp 3 for all export format.

@khaledhosny please review the plan before I start.

**Comment by khaledhosny** [comment]
For a first iteration I’d go for a simple CSS-like approach; the font setting should take a list of font names and the code would just try the fonts in the list in their order.

I’m make the handling of the fallback part of the layout and pass the font used by each glyph down to the renders rather than duplicating the logic there.

Also when a character is not supported by the font (0 glyph index), you should use the whole grapheme cluster with the fallback font otherwise you might get broken results with many complex scripts (or even non-complex, like a e with accent but the font does not have the accent, doing fallback for the accent only with give bad looking result, instead you should do the fallback or both the e and the accent at the same time).

Later we can add support for different fonts per language, so one can say I want to use say Times New Roman as main font, but use Scheherazade for Arabic etc. and then Scheherazade would be used for Arabic even though Times New Roman has Arabic characters. This IMO is more flexible and matches more the needs of multilingual typography when you often want specific fonts for different languages/scripts regardless of which languages are supported by other fonts.

**Comment by Fahad-Alsaidi** [comment]
Thanks @khaledhosny  for your great  feedback. I have a question here, should font fallback (the first part) saved as a style, thus it will be saved in scribus format? or should font fallback feature change the font for missing faces silently? 
@aoloe & @MrB74 your feedback are welcome.

**Comment by aoloe** [comment]
my point of view is from somebody that uses multiple "latin" languages and has no real clue with other scripts (other than hearsay... and interacting with this project...).
my opinion is worth what it is worth... please, take it with a grain of salt.

first, what i would personally need: an easy way to define a language for single words, mostly for hyphenation and spell checking purposes.
of course, when only using latin languages, i don't think it makes sense to have different fonts for different languages (well, it would be nice to have "c++" as a language and get syntax highlighting and linting making sure that your snippets are correct... many programming books could profit from it... but i disgress : - )
(missing diacritics or en-dashes might be a usage... but i'm not 100% sure that it really makes sense.)

that being said -- and back to the fallback issue --, i think that i would prefer manually setting the font for each language, rather than having an automatic fallback by language when a glyph is missing.
missing glyphs should be highlighted by the preflight verifier (an interactive warning could also be an option) and the user should than pick the right font for the right language.
IMO that would lead to a more straight forward implementation.

the next point is about the UI.

how to let scribus know which language is being used and what is the font to be used?
hard to say.
if i understand you correctly, you're proposing to add a per language  switch in the character style / properties palette.
but:
different fonts should probably have different sizes...
and maybe, you would want to have different character / word spacing (because it's a different font).
that switch could get complex.
and we could have more than two scripts in use (latin, indic and arabic could be easily found in the same text...)

worth to be explored: using different fonts for different code ranges? (and so indipendent from the language)

another possible solution: implement it as (a cascade of inheriting) character styles, rather than variations inside of a character style.
and then make it easy to apply character styles.

sorry, i have no solution... only more questions : - (

(positing this for now, even if it's not a definitive contribution)

**Comment by khaledhosny** [comment]
> should font fallback (the first part) saved as a style, thus it will be saved in scribus format? or should font fallback feature change the font for missing faces silently? 

Do you mean the list of the fonts that the user chooses, or the actual fallback (which character came from which font)? The former should be part of the document, but the later not IMO as it can change when the user installs new version of the fonts etc. so it shouldn’t be hard coded.

**Comment by Fahad-Alsaidi** [comment]
> but the later not IMO as it can change when the user installs new version of the fonts etc. so it shouldn’t be hard coded.

so, when the user choose a font fallback for text frame, scribus will reshape that text frame and set font for missing faces to the new chosen font fallback?

**Comment by Fahad-Alsaidi** [comment]
WIP! 
![output](https://cloud.githubusercontent.com/assets/1632566/20298552/04a35c24-ab30-11e6-81d7-2fb2274491f8.gif)

any feedback are welcome.

**Comment by aoloe** [comment]
looks nice!

but what will you do if you need a fallback for both hindi and arabic?

personally, i still would suggest to think about a feature based alternate font selection instead of an automatic fallback...
as an example, in this way you could also switch the font when the current font has the feature but it's not well done.
do you know if a "code ranges" approach could be possible or not?

**Comment by aoloe** [comment]
(sorry, submitted too early)

anyway, i can leave (very well!) with your proposal.

i'm not against it at all, i just wonder if exploring new ways could lead to even a better result.

**Comment by Fahad-Alsaidi** [comment]
> but what will you do if you need a fallback for both hindi and arabic?

Obviously, first you should use a font support both. If you don't have it, Khaled's suggestion, which is adding support for different fonts per language, will help here. What I am planing to achieve it after complete fallback part:
1. scan the story text and find which languages (or at least scripts) are used. 
2. add a new section under text setting call languages and list all used languages.
3. from there specify which font you want to use per language.

**Comment by khaledhosny** [comment]
The fallback should be at least list of fonts, not just a single font.

**Comment by aoloe** [comment]
i try to reformulate my question : - )
- can the "missing glyph" errors be summarized in "code ranges" (in most cases only one code range)?  
  (i think so, but -- as said -- my experience/needs is "smaller" and very different than yours!)
- would a "manual" and per "code range" solution work for arabic / your use?

personally, i mostly prefer good manual switches, with a good UI, to automatic solutions that have a hard time with corner cases.

for my use cases (using poor google fonts with missing glyphs), i would prefer a tooltip on the missing box glyph + an error in the preflight verifier, with an hint that tells me how to solve the issue (which code page is not complete, link to the missing glyph from the preflight verifier).

**Comment by Fahad-Alsaidi** [comment]
> can the "missing glyph" errors be summarized in "code ranges" (in most cases only one code range)?
> (i think so, but -- as said -- my experience/needs is "smaller" and very different than yours!)

Yes.

> would a "manual" and per "code range" solution work for arabic / your use?

Yes.

to be clear here, we talk about two things:
1. Automatic solution (the original fall back feature). This what I am now working on. You just need to set fallback fonts and done.
2. manual solution (font per language). [This](https://github.com/HOST-Oman/scribus/issues/110#issuecomment-260591840) better but requires more work.

**Comment by aoloe** [comment]
ok, thanks for the explaination, fahad!

**Comment by Fahad-Alsaidi** [comment]
By [this](https://github.com/HOST-Oman/scribus/commit/39fff8320facc88b9cc2c67012698524d3d7db95) I have  finished the automatic solution (the original fall back feature) except the ability to select multi fonts which requires a new GUI widget to do that, IMHO.
If every thing fine, I will move to the second part font per language.

**Comment by Fahad-Alsaidi** [comment]
the second part, WIP

![scripts](https://cloud.githubusercontent.com/assets/1632566/20515480/5473fca6-b0ab-11e6-8c58-5fd4a92e918b.jpg)

Your feedback are welcomed.

**Comment by aoloe** [comment]
looks nice!
i would be really happy, if we can avoid the automatic fallback...

on other thing: i wonder if we could simply have the list of scripts between the font picker and the font size... i don't feel like adding yet another sub tab...
but this is something that could be changed after the new properties palette will be integrated in 1.5.4...
