### ISSUE TITLE
Full Justification icon is misleading when paragraph is RTL

### ISSUE THREAD

**Issue by zayedalsaidi** [HOST-Oman/scribus#161]
when apply full justification for Arabic text, the last line in the paragraph is suppose to be right justify.

![scribus-full-justifaction](https://cloud.githubusercontent.com/assets/18646956/14769602/f83d1dc6-0a6c-11e6-98bf-39f676334c13.png)

Here is the test file

[arabic justifaction.sla.tar.gz](https://github.com/HOST-Oman/scribus/files/233586/arabic.justifaction.sla.tar.gz)

**Comment by khaledhosny** [comment]
I’m no sure what the problem is, the alignment looks correct. Can you attach a simpler document with just one paragraph showing the issue?

**Comment by Fahad-Alsaidi** [comment]
After testing the file, I can confirm that the full Justification is working fine. I think what you want is "Align text Justified " 
However, I admit the icon for "Align text Justified " is confusing right now because it seems for "**left**" Align text Justified but in fact it works for RTL and LTR.
I think we should divide it to two icons one for left align justified text and one for right align justified text.

**Comment by khaledhosny** [comment]
Or we can have an alternate icon and modify the widget to use the alternate icon when the paragraph direction is RTL, @Fahad-Alsaidi can you give this a try?

**Comment by zayedalsaidi** [comment]
The icon is confusing :). I think @khaledhosny suggestion is good enough.
