### ISSUE TITLE
Hyphenation did not work for Malayalam

### ISSUE THREAD

**Issue by santhoshtr** [HOST-Oman/scribus#177]
I copied the hyphenation rules to the folder /usr/local/share/scribus/dicts/hyph. I use the https://github.com/smc/hyphenation/blob/master/ml_IN/hyph_ml_IN.dic and renamed to hyph_ml.dic

In document properties, under hyphenation, Malayalam was now listed, and I selected it.

Added a text frame with Malayalam text, justified it , from menu tried Hyphenation. Did not see any change in the selected text frame.

**Comment by khaledhosny** [comment]
Can you please attach a test document?

**Comment by rajeeshknambiar** [comment]
FYI - after copying the hyph_ml.dic into hyphenation directory, it works as expected for me. Attached screenshot.
![scribus-malayalam-hyphen-1 5 1](https://cloud.githubusercontent.com/assets/424259/15075107/ed4fa7c8-13a2-11e6-83d4-6abdc80de025.jpeg)

**Comment by rajeeshknambiar** [comment]
Test document attached.

[Koodu-Magazine-Manoj.sla.zip](https://github.com/HOST-Oman/scribus/files/252346/Koodu-Magazine-Manoj.sla.zip)

**Comment by khaledhosny** [comment]
@rajeeshknambiar document works for me as well after installing the dictionary and hyphenating the text. Note that the hyphenation language is taken from the text language not from the hyphenator preferences (the UI is misleading) so you should go to Windows→Properties→Text and select Malayalam.

**Comment by khaledhosny** [comment]
Renaming the hyphenation dictionary should not be needed now.

**Comment by santhoshtr** [comment]
Ok, After setting the language as Malayalam using Windows→Properties→Text worked for me.

> Renaming the hyphenation dictionary should not be needed now.

Thanks!

Now, to make the hyphenation perfect, is there a way we can specify the hyphenation character? To be specific, Malayalam does not need visible hyphen character. (If this is not possible and not reported as a bug, I can create a new bug).

**Comment by khaledhosny** [comment]
You can’t currently select the hyphenation character, but please open an issue for that as it is something I’d like to support.

**Comment by santhoshtr** [comment]
Filed #178 for custom hyphenation character. 
Closing this ticket.

**Comment by pinarayi** [comment]
Hyphenation is not working in version 1.5.3

**windows**

I copied the hyphenation rules to the folder /PROGRAM FILES/scribus 1.5.3/share/scribus/dicts/hyph. I used the https://github.com/smc/hyphenation/blob/master/ml_IN/hyph_ml_IN.dic
In Windows -> Text properties selected malayalam

Selected Extras-> Hyphenate Text .

It gives following error.
Scribus crashes dues following exception:EXCEPTION_ACCESS_VIOLATION


**Ubuntu**

Downloaded and copied

https://github.com/smc/hyphenation/blob/master/ml_IN/hyph_ml_IN.dic

to /usr/local/share/scribus-ng/dicts/hyph

In Windows -> Text properties selected malayalam

Selected Extras-> Hyphenate Text . Then the error "Scribus crashed due to Signal#11 " comes.

**Comment by aoloe** [comment]
@pinarayi i think that you should try to (correctly) add the hyphenation files to the scribus sources and then compile scribus with them.
i don't know the details, but you will probably have to add them to the cmake file, too... and check that the format is indeed the same as for the other hyphenation files already in use in scribus.

you should probably fill a ticket on https://bugs.scribus.net ...
