### ISSUE TITLE
Allow customization of hyphenation character

### ISSUE THREAD

**Issue by santhoshtr** [HOST-Oman/scribus#178]
Malayalam hyphenation should not show a visible hyphen at line breaks. While using xelatex, we often set HyphenChar as some invisible character to get this effect. 

It would be great if scribus can allow setting hyphenation character.

**Comment by khaledhosny** [comment]
I think we will need to first cleanup hyphenation settings and make it a character style, then add a new style for the hyphenation character.

**Comment by khaledhosny** [comment]
So here is my current plan if anyone wants to help with it:
- Add character styles for hyphenation settings:
  - Enable hyphenation
  - Smallest word
  - Consecutive hyphens allowed (probably should be a paragraph style)
  - Left hyphen min (new)
  - Right hyphen min (new)
- Add UI for setting the new styles.
- Move hyphenation to the text shaper:
  - Collect possible hyphenation points before itemizing text, store them and a vector and don’t set any flags to the story text.
  - Set `ScLayout_HyphenationPossible` flags on the glyph clusters based on the above vector.
- `PageItem_TextFrame::layout()` will need to honour the new consecutive hyphens.

At this point most of the old hyphenation code can go away.

This way we can properly handle hyphenation settings for different languages in the same document.

Then:
- Add a new character style for hyphen character and adapt the code to use it instead of always trying hyphen/hyphen-minus as it does now.

**Comment by khaledhosny** [comment]
Thinking about this more, I think moving the hyphenation to the shaper is not needed to address the current issue; we can use the new styles with the existing hyphenation class, we already read the hyphenation language from the character style.

**Comment by andreas-vox** [comment]
I'm also in favor of not adding hyphenation code to the shaper. Identifying hyphenation points should be a StoryText responsibility, using hyphenation points a responsibility of the layouter.

**Comment by khaledhosny** [comment]
IMHO, hyphenation should be done as part of the layout, needing a separate action to do the hyphenation (currently one has to go to Extras → Hyphenate Text) is something I never seen before except in Scribus. The best place to do that during the layout is the shaper. The actual code can be ib StoryText, though I personally don’t think hyphenation points is some thing that needs to be stored with the text. If I install a better hyphenation dictionary, change the language, install hyphenation dictionary where none was available before I expect the layout to make use of it with no additional steps, but saving the hyphenation points with the text just complicates this with no much benefit.

**Comment by khaledhosny** [comment]
This is now supported, please test and reopen if there are any issues:
![2016-05-14 23-52-23](https://cloud.githubusercontent.com/assets/93914/15270870/87eb46bc-1a37-11e6-9592-6ac4b0a8165c.png)

**Comment by Fahad-Alsaidi** [comment]
what is Samlest Word?

**Comment by khaledhosny** [comment]
The smallest word to be hyphenated (i.e. words less than 3 letters will not be hyphenated). This is just moved from the old hyphenation preferences tab.

**Comment by santhoshtr** [comment]
I did 
``
$ cmake .
[...]
Hunspell Found OK
[...]
$ make
[...]
Scanning dependencies of target hunspellplugin
[ 97%] Building CXX object scribus/plugins/tools/hunspellcheck/CMakeFiles/hunspellplugin.dir/hunspelldialog.cpp.o
[ 97%] Building CXX object scribus/plugins/tools/hunspellcheck/CMakeFiles/hunspellplugin.dir/hunspellplugin.cpp.o
[ 98%] Building CXX object scribus/plugins/tools/hunspellcheck/CMakeFiles/hunspellplugin.dir/hunspellpluginimpl.cpp.o
[ 98%] Building CXX object scribus/plugins/tools/hunspellcheck/CMakeFiles/hunspellplugin.dir/moc_hunspelldialog.cpp.o
make[2]: **\* No rule to make target '/usr/lib/x86_64-linux-gnu/libhunspell-1.3.so', needed by 'scribus/plugins/tools/hunspellcheck/libhunspellplugin.so'.  Stop.
CMakeFiles/Makefile2:4395: recipe for target 'scribus/plugins/tools/hunspellcheck/CMakeFiles/hunspellplugin.dir/all' failed
make[1]: **\* [scribus/plugins/tools/hunspellcheck/CMakeFiles/hunspellplugin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: **\* [all] Error 2

```

Then I did

``
santhosh@thottingal scribus (ctl)$ sudo ln -s /usr/lib/x86_64-linux-gnu/libhunspell-1.3.so.0 /usr/lib/x86_64-linux-gnu/libhunspell-1.3.so
```

and everything worked fine and successfully installed.

Opened scribus and tried to customize the character by pressing backspace in the hyphenation field.
Scribus crashed. In the console I see

```
Scribus Crash
-------------
Scribus crashes due to Signal #11
Segmentation fault
```

Let me know any more details you need about this issue. Happy to help.
I am using Debian Unstable, KDE Plasma desktop, my scribus is at 96a55c8c7cc04b8714e53ba43cb6af0147251acf

**Comment by khaledhosny** [comment]
Was this a clean build? CMake caches seems to not get purged when stuff changes, so you would better start with a clean build. Calling `git clean -fd .` should remove any build files, and then start over again. If the crash pesists then I’ll need a tracback (on systems using systemd, you can call `coredumpctl gdb` just after the crash to get it, otherwise run Scribus inside gdb).

**Comment by Fahad-Alsaidi** [comment]
@khaledhosny then samlest is a typo.

**Comment by khaledhosny** [comment]
Fixed the typo.
