### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by pathumego** [HOST-Oman/scribus#9]
Hi, 

Im very interested in helping implementing CTL features. I can test on Mac, Win and GNU systems. Where can I find build instructions for this? If there is a clear and fast way to test out code from this repo I can make sure everything is tested as the new features are pushed. 

Thanks for the efforts!

**Comment by khaledhosny** [comment]
We currently have two active branches, `boxes` where we are preparing the code base for CTL support but no actual CTL work is done. Testing this branch should focus on finding regressions compared to the master branch (which tracks upstream SVN head).

There is another `ctl` branch that adds the required CTL support, it is in early state and I need to rebase it on `boxes` branch. I think this branch should be ready for testing in a week or so, since I’m currently doing some refactoring before resuming work on it.

Build instructions for both should be essentially the same as Scribus SVN, with the CTL branch requiring also HarfBuzz and ICU.

**Comment by luzpaz** [comment]
OSX users who want a quick way to build could use:
`brew update && brew upgrade --all`
`brew install --HEAD https://gist.githubusercontent.com/luzpaz/e8fe95ec72b746966e6f/raw/55f58c0b58da649d1c95bbda935ddff49ae3949c/scribusctlboxes.rb --verbose`
and to reinstall just swap out `install` for `reinstall`

**Comment by khaledhosny** [comment]
Thanks @luzpaz for the Homebrew formula, much appreciated.
